Repository PrefectHQ/prefect-helm, pull requests merged in 2022-10, with the labels that each got.

#69 feat: automate version bumps of dependent bitnami helm charts
  .github/updatecli/manifest.yaml
  .github/workflows/update-helm-versions.yaml
  charts/prefect-orion/Chart.yaml
  charts/prefect-orion/README.md
Labels: enhancement, maintenance

#67 Provide writable directories by default
  Readme.md
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-orion/templates/deployment.yaml
Labels: fix

#71 feat: add support for passing additional permissions to the agent role
  Readme.md
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/role.yaml
  charts/prefect-agent/values.yaml
Labels: feature
