Repository PrefectHQ/prefect-helm, pull requests merged in 2022-09, with the labels that each got.

#34 Administrative Cleanup
  .github/CODEOWNERS
  .github/linters/ct.yaml
  .github/release.yaml
  .github/workflows/helm-release.yaml
  .github/workflows/helm_release.yaml
  .github/workflows/linting.yaml
  charts/prefect-agent/Chart.yaml
  charts/prefect-agent/README.md
  charts/prefect-orion/Chart.yaml
  charts/prefect-orion/README.md
  charts/prefect-orion/values.yaml
Labels: maintenance

#37 hotfix: fixed pathing for chart releases in index file
  .github/workflows/helm-release.yaml
Labels: maintenance

#38 [orion] Fix pathing reference to postgresql.auth.existingSecret
  charts/prefect-orion/templates/_helpers.tpl
  charts/prefect-orion/templates/api/secret.yaml
Labels: fix

#39 [orion] Updates pathing for postgresql user
  charts/prefect-agent/README.md
  charts/prefect-orion/README.md
  charts/prefect-orion/values.yaml
Labels: fix

#41 Add the ability to customize labels attached to resources
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/_helpers.tpl
  charts/prefect-agent/values.yaml
  charts/prefect-orion/README.md
  charts/prefect-orion/templates/_helpers.tpl
  charts/prefect-orion/values.yaml
Labels: enhancement

#43 fix: use prefect agent start -q
  charts/prefect-agent/templates/agent/deployment.yaml
Labels: enhancement

#45 [agent] chart overhaul
  .github/linters/agent-ct.yaml
  .github/linters/orion-ct.yaml
  .github/workflows/agent-lint-and-test.yaml
  .github/workflows/linting.yaml
  .github/workflows/orion-lint-and-test.yaml
  charts/prefect-agent/Chart.yaml
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/NOTES.txt
  charts/prefect-agent/templates/_helpers.tpl
  charts/prefect-agent/templates/agent/deployment.yaml
  charts/prefect-agent/templates/agent/rbac.yaml
  charts/prefect-agent/templates/agent/role.yaml
  charts/prefect-agent/templates/agent/serviceaccount.yaml
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/templates/role.yaml
  charts/prefect-agent/templates/rolebinding.yaml
  charts/prefect-agent/templates/serviceaccount.yaml
  charts/prefect-agent/values.yaml
  charts/prefect-orion/README.md
  charts/prefect-orion/values.yaml
Labels: enhancement, breaking

#46 [agent] Add support for running unprivileged
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/values.yaml
Labels: enhancement

#48 [orion] chart overhaul
  charts/prefect-orion/.helmignore
  charts/prefect-orion/Chart.yaml
  charts/prefect-orion/README.md
  charts/prefect-orion/templates/NOTES.txt
  charts/prefect-orion/templates/_helpers.tpl
  charts/prefect-orion/templates/api/deployment.yaml
  charts/prefect-orion/templates/api/hpa.yaml
  charts/prefect-orion/templates/api/ingress.yaml
  charts/prefect-orion/templates/api/secret.yaml
  charts/prefect-orion/templates/api/service.yaml
  charts/prefect-orion/templates/api/serviceaccount.yaml
  charts/prefect-orion/templates/deployment.yaml
  charts/prefect-orion/templates/hpa.yaml
  charts/prefect-orion/templates/ingress.yaml
  charts/prefect-orion/templates/secret.yaml
  charts/prefect-orion/templates/service.yaml
  charts/prefect-orion/templates/serviceaccount.yaml
  charts/prefect-orion/values.yaml
Labels: enhancement, breaking

#49 [orion] Add support for running unprivileged
  charts/prefect-orion/README.md
  charts/prefect-orion/templates/deployment.yaml
  charts/prefect-orion/templates/service.yaml
  charts/prefect-orion/values.yaml
Labels: enhancement

#51 Update versioning & release workflow
  .github/workflows/helm-release.yaml
  charts/prefect-agent/Chart.yaml
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/values.yaml
  charts/prefect-orion/Chart.yaml
  charts/prefect-orion/README.md
  charts/prefect-orion/templates/deployment.yaml
  charts/prefect-orion/values.yaml
Labels: maintenance

#52 [orion] persistence nesting fix
  Readme.md
  charts/prefect-orion/README.md
  charts/prefect-orion/values.yaml
Labels: fix

#55 [agent] Allow toggling attachment of apiKeySecret to agent container
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/values.yaml
Labels: fix

#56 Add appVersion to labels of all resources
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/templates/role.yaml
  charts/prefect-agent/templates/rolebinding.yaml
  charts/prefect-agent/templates/serviceaccount.yaml
  charts/prefect-orion/templates/deployment.yaml
  charts/prefect-orion/templates/hpa.yaml
  charts/prefect-orion/templates/ingress.yaml
  charts/prefect-orion/templates/secret.yaml
  charts/prefect-orion/templates/service.yaml
  charts/prefect-orion/templates/serviceaccount.yaml
Labels: enhancement

#58 [agent] Adjust agent configuration settings
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/NOTES.txt
  charts/prefect-agent/templates/_helpers.tpl
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/values.yaml
Labels: enhancement, breaking

#59 [agent] expose additional configuration
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/values.yaml
Labels: enhancement

#60 pass `appVersion` to container labels
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-orion/templates/deployment.yaml
Labels: fix

#61 Fix a typo when checking the support for ingress classname in orion
  charts/prefect-orion/templates/ingress.yaml
Labels: fix

#66 [orion] Fix ingress servicePort reference
  charts/prefect-orion/templates/ingress.yaml
Labels: fix
