Repository PrefectHQ/prefect-helm, pull requests merged in 2024-07, with the labels that each got.

#353 fix: servicemonitor additionalLabels
  charts/prometheus-prefect-exporter/templates/servicemonitor.yaml
Labels: fix

#354 feat(charts): support securityContext.capabilities
  charts/prefect-agent/README.md
  charts/prefect-agent/templates/deployment.yaml
  charts/prefect-agent/values.schema.json
  charts/prefect-agent/values.yaml
  charts/prefect-server/README.md
  charts/prefect-server/templates/deployment.yaml
  charts/prefect-server/values.schema.json
  charts/prefect-server/values.yaml
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: feature

#355 chore: manage tool versions
  .mise.toml
  README.md
Labels: enhancement

#357 feat(prefect-worker): update Base Job Template with user-provided JSON
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/deployment.yaml
Labels: feature

#361 feat(prefect-worker): configure resources on initContainer
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: enhancement

#356 chore(prometheus-prefect-exporter): make further use of common library chart
  charts/prometheus-prefect-exporter/README.md
  charts/prometheus-prefect-exporter/templates/NOTES.txt
  charts/prometheus-prefect-exporter/templates/_helpers.tpl
  charts/prometheus-prefect-exporter/templates/deployment.yaml
  charts/prometheus-prefect-exporter/templates/hpa.yaml
  charts/prometheus-prefect-exporter/templates/pdb.yaml
  charts/prometheus-prefect-exporter/templates/prometheusrule.yaml
  charts/prometheus-prefect-exporter/templates/service.yaml
  charts/prometheus-prefect-exporter/templates/serviceaccount.yaml
  charts/prometheus-prefect-exporter/templates/servicemonitor.yaml
  charts/prometheus-prefect-exporter/templates/tests/test-connection.yaml
  charts/prometheus-prefect-exporter/values.yaml
Labels: maintenance

#363 feat(prefect-worker): support initContainer securityContext
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: breaking
