Repository PrefectHQ/prefect-helm, pull requests merged in 2024-11, with the labels that each got.

#389 Add option for setting nodePort for LoadBalancers
  charts/prefect-server/templates/service.yaml
  charts/prefect-server/tests/server_test.yaml
Labels: enhancement

#411 Remove unintentional README update
  README.md
Labels: docs

#412 chore: update depbot to apply consistent label to all PRs
  .github/dependabot.yaml
Labels: maintenance

#413 fix: correctly reference `ingress.servicePort` within `range`
  charts/prefect-server/templates/ingress.yaml
Labels: fix

#416 Add `provenance` docs
  README.md
Labels: docs
