Repository PrefectHQ/prefect-helm, pull requests merged in 2024-05, with the labels that each got.

#328 [exporter]: bump default image tag to `1.1.0`
  charts/prefect-agent/README.md
  charts/prefect-server/README.md
  charts/prefect-worker/README.md
  charts/prometheus-prefect-exporter/README.md
  charts/prometheus-prefect-exporter/values.yaml
Labels: enhancement

#329 chore: add exporter label to release
  .github/release.yaml
Labels: maintenance

#330 Introduce automation for releases
  .github/workflows/deploy-latest-helm-version.yaml
  .github/workflows/helm-release.yaml
  .github/workflows/prometheus-exporter-helm-release.yaml
Labels: maintenance

#332 chore/Add default requests and limits to prefect server
  charts/prefect-server/values.yaml
Labels: breaking

#333 chore(prometheus-prefect-exporter): Add additionalLabels for serviceMonitor
  charts/prometheus-prefect-exporter/README.md
  charts/prometheus-prefect-exporter/templates/servicemonitor.yaml
  charts/prometheus-prefect-exporter/values.schema.json
  charts/prometheus-prefect-exporter/values.yaml
Labels: exporter

#340 Allow an existing ConfigMap to be passed for `baseJobTemplate`
  .pre-commit-config.yaml
  charts/prefect-agent/README.md
  charts/prefect-server/README.md
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/_helpers.tpl
  charts/prefect-worker/templates/configmap.yaml
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
  charts/prometheus-prefect-exporter/README.md
Labels: enhancement, breaking
