Repository PrefectHQ/prefect-helm, pull requests merged in 2025-02, with the labels that each got.

#437 fix(actions): adjust job name for mise workflow
  .github/workflows/notify-on-failure.yaml
  .github/workflows/update-mise-tools.yaml
Labels: maintenance

#446 chore(docs): document how to set imagePullSecrets in baseJobTemplate
  charts/prefect-worker/README.md
  charts/prefect-worker/README.md.gotmpl
Labels: docs

#447 chore: remove exporter & server downstream repo updates
  .github/workflows/helm-release.yaml
  .github/workflows/prometheus-exporter-helm-release.yaml
Labels: maintenance

#448 Add PREFECT_API_AUTH_STRING to init container
  charts/prefect-worker/templates/deployment.yaml
Labels: fix

#449 feat(prefect-server): add custom entrypoint and args
  charts/prefect-server/README.md
  charts/prefect-server/templates/server-deployment.yaml
  charts/prefect-server/tests/server_test.yaml
  charts/prefect-server/values.schema.json
  charts/prefect-server/values.yaml
Labels: enhancement

#451 chore: turn off automatic releases by requiring inputs
  .github/workflows/helm-release.yaml
Labels: maintenance

#455 chore: add pull request template
  .github/pull_request_template.md
Labels: maintenance

#453 breaking change: update self-hosted server references to be consistent across the `worker` chart
  charts/prefect-worker/README.md
  charts/prefect-worker/README.md.gotmpl
  charts/prefect-worker/UPGRADING.md
  charts/prefect-worker/templates/NOTES.txt
  charts/prefect-worker/templates/_helpers.tpl
  charts/prefect-worker/tests/worker_test.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: breaking

#450 breaking change: remove confusing & duplicative environment variables
  charts/prefect-server/README.md
  charts/prefect-server/UPGRADING.md
  charts/prefect-server/templates/NOTES.txt
  charts/prefect-server/templates/_helpers.tpl
  charts/prefect-server/templates/_validation.tpl
  charts/prefect-server/templates/background-services-deployment.yaml
  charts/prefect-server/templates/server-deployment.yaml
  charts/prefect-server/tests/background_services_test.yaml
  charts/prefect-server/tests/server_test.yaml
  charts/prefect-server/values.schema.json
  charts/prefect-server/values.yaml
Labels: breaking

#458 chore(docs): add context to background services
  charts/prefect-server/README.md
  charts/prefect-server/README.md.gotmpl
Labels: docs

#456 breaking changes: update `basicAuth` settings to be nested under the right `selfHostedServerApiConfig` key
  charts/prefect-server/templates/server-deployment.yaml
  charts/prefect-worker/README.md
  charts/prefect-worker/UPGRADING.md
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/tests/worker_test.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: breaking
