Repository PrefectHQ/prefect-helm, pull requests merged in 2025-09, with the labels that each got.

#538 Add version requirement warning for separated background services
  charts/prefect-server/README.md
  charts/prefect-server/README.md.gotmpl
Labels: docs

#540 fix(server): only run db migration hook in multi-server mode
  charts/prefect-server/templates/pre-upgrade-hook.yaml
  charts/prefect-server/tests/pre_upgrade_hook_test.yaml
Labels: bug

#549 feat(server): Add support for tolerations, nodeSelector and affinity for migrations job
  charts/prefect-server/README.md
  charts/prefect-server/templates/pre-upgrade-hook.yaml
  charts/prefect-server/tests/pre_upgrade_hook_test.yaml
  charts/prefect-server/values.schema.json
  charts/prefect-server/values.yaml
Labels: feature

#547 feat(exporter): more flexible configuration of env vars on deployment
  charts/prometheus-prefect-exporter/README.md
  charts/prometheus-prefect-exporter/templates/deployment.yaml
  charts/prometheus-prefect-exporter/tests/exporter_test.yaml
  charts/prometheus-prefect-exporter/values.schema.json
  charts/prometheus-prefect-exporter/values.yaml
Labels: feature
