Repository PrefectHQ/prefect-helm, pull requests merged in 2025-01, with the labels that each got.

#423 chore(CI): fix logic for finding prefect version
  .github/workflows/helm-release.yaml
Labels: maintenance

#422 feat(worker): support env vars from multiple ConfigMaps, Secrets
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/tests/worker_test.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: enhancement

#428 fix(appVersion): adjust refs to prefect version 3
  README.md
  charts/prefect-server/Chart.yaml
  charts/prefect-worker/Chart.yaml
Labels: docs, maintenance

#431 chore(docs): add upgrade guide for prefect-server
  charts/prefect-server/UPGRADING.md
Labels: docs

#433 Add value for PREFECT_CLOUD_API_URL to worker chart for Self Managed Cloud instances
  charts/prefect-server/README.md
  charts/prefect-worker/README.md
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
  charts/prometheus-prefect-exporter/README.md
Labels: enhancement

#434 [worker] update chart to reference `self-managed` rather than `self-hosted` for Self Managed Cloud
  .mise.toml
  charts/prefect-worker/README.md
  charts/prefect-worker/README.md.gotmpl
  charts/prefect-worker/UPGRADING.md
  charts/prefect-worker/templates/_helpers.tpl
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/tests/worker_test.yaml
  charts/prefect-worker/values.schema.json
  charts/prefect-worker/values.yaml
Labels: breaking
