Repository PrefectHQ/prefect-helm, pull requests merged in 2025-08, with the labels that each got.

#514 feat(exporter): pass annotations for service via values
  charts/prometheus-prefect-exporter/README.md
  charts/prometheus-prefect-exporter/templates/service.yaml
  charts/prometheus-prefect-exporter/tests/exporter_test.yaml
  charts/prometheus-prefect-exporter/values.schema.json
  charts/prometheus-prefect-exporter/values.yaml
Labels: feature, exporter

#515 chore: remove empty Makefile
  Makefile
Labels: maintenance

#532 feat(server): add Helm hook for database migrations when running in multi-server mode
  charts/prefect-server/README.md
  charts/prefect-server/README.md.gotmpl
  charts/prefect-server/UPGRADING.md
  charts/prefect-server/templates/_helpers.tpl
  charts/prefect-server/templates/pre-upgrade-hook.yaml
  charts/prefect-server/tests/background_services_test.yaml
  charts/prefect-server/tests/pre_upgrade_hook_test.yaml
  charts/prefect-server/values.schema.json
  charts/prefect-server/values.yaml
Labels: enhancement, feature
