Repository PrefectHQ/prefect-helm, pull requests merged in 2025-03, with the labels that each got.

#463 feat: Update worker to pass API key to created jobs via Kubernetes secret
  charts/prefect-worker/templates/deployment.yaml
  charts/prefect-worker/tests/worker_test.yaml
Labels: enhancement

#464 chore(docs): Finalize upgrade docs for breaking change release
  charts/prefect-server/UPGRADING.md
  charts/prefect-worker/UPGRADING.md
Labels: docs

#465 chore(docs): Update `version` ref in upgrading docs
  charts/prefect-server/UPGRADING.md
  charts/prefect-worker/UPGRADING.md
Labels: maintenance

#469 fix(ci): pin `helm-unittest` version
  .github/workflows/helm-unittest.yaml
  scripts/helm_unittest.sh
Labels: maintenance

#472 chore: remove release gate
  .github/workflows/helm-release.yaml
Labels: maintenance
